name: persistent
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: ^4.7.0
  build: ^2.3.0
  code_builder: ^4.2.0
  source_gen: ^1.2.2
  persistent_annotation:
    path: ../persistent_annotation
  dart_style: ^2.2.3

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^2.0.0
